Add http client and align his method with custom hook.
claranet-it/library-manager pull request #52
Opened 2023-01-26 13:53 UTC by EmanueleGurini

## What is inside this PR?
- Added an API client that exposes methods for each route

- The API client is a class that extends the HTTP one. To maintain the single responsibility pattern, we created a service class that manages the logic behind the creation of the URL for the getBooks.

- Custom hooks are no longer handling page logic. We refactored the custom hooks by moving everything related to pages inside them.

2023-01-31 11:11 UTC, slash-84 requested changes

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/types.d.ts
> +export type TData = {
I suggest you a more meaningful name, like `PaginatedData`

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/types.d.ts
> +  data: Book[];
since this type is global and not strictly related to `Book`, i suggest to use generics (e.g. `PaginatedData<Book>`)

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/utils/ApiClient.ts
> +export class ApiClient extends HttpMethods {
This class should not extend `HttpMethods`, in a previous review we decided to not export it in favor of the instance. Try to use composition. Also check the class name, if its responsibility is to "work with books over http" give it a more meaninful name, like `BookClient`

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/utils/ApiClient.ts
> +  public async getBooks(URL: string): Promise<TData> {
URL handling should be inside this class, the user of this class should not know the endpoint

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/utils/ApiClient.ts
> +  public async updateBook(id: string, body: Book): Promise<Book> {
`id` is already in the `Book` type, you can avoid the usage of the first argument

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/utils/ServiceClass.ts
> +export class ApiClientService {
This class could be deleted. Read other PR comments and work with composition for book client, I guess you will not need it any more :-)

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/utils/http-methods.ts
> +export class HttpMethods {
leave this class private, remove the export

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/utils/http-methods.ts
> -export const HTTP = new HttpMethods();
restore this export and try to work with composition and use the HTTP instance instead of inheritance

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/views/create/index.tsx
> +  const handleSubmit = (values: Omit<Book, 'id'>) => {
Handle submit vs createBook, why 2 functions? One is enough

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/views/create/index.tsx
> +    navigate('/', { replace: true });
No error handling

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/views/create/index.tsx
> +  if (error.isError) return <div>{error.message}</div>;
What happens if there is an error? How the user can recover the app or if we want the error inside a popup? Think about it ;)

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/views/create/index.tsx
> +              }
Why regex?

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/views/detail/index.tsx
> +    return <p> Id non definito </p>;
not sure you really need it

2023-01-31 11:11 UTC, slash-84 commented on frontend/src/views/edit/index.tsx
> +    return <p> Id non definito </p>;
not sure you really need it

2023-01-31 13:48 UTC, slash-84 requested changes

2023-01-31 13:48 UTC, slash-84 commented on frontend/src/views/home/index.tsx
>  function Home() {
Regression found.
Try to find it as an exercise.

Hint: set a LIMIT that will shows up pagination, then change page. What happens?

2023-02-01 15:05 UTC, mariateresagraziano commented on frontend/src/views/create/index.tsx
> +              }
Perchè abbiamo pensato ci sia un maggior controllo sugli input

2023-02-02 09:50 UTC, slash-84 approved these changes
Approved with conditions - we'll merge the PR and in the next lesson(s) we'll discuss about the whole codebase in general.

2023-02-02 09:51 UTC, slash-84 approved these changes
Approved with conditions - we'll merge the PR and in the next lesson(s) we'll discuss about the whole codebase in general.

2023-02-02 09:53 UTC, merged